version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: ec2-user
