version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo
hooks:
  AfterInstall:
    - location: Scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: Scripts/start_pm2.sh
      timeout: 300
      runas: ec2-user