version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/StoresAdminPanel
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 600
      runas: ubuntu
