version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/StoresAdminPanel
hooks:
  BeforeInstall:
    - location: prod/scripts/clean.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: prod/scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: prod/scripts/start_pm2.sh
      timeout: 600
      runas: ubuntu
