export const MigrationDefaultKeys = [
    "products",
    "categories",
    "contents",
    "sections",
    "orders",
  ];
  
  export const colorPalettes = {
    Light: {
      pri: "#FFFFFF",
      sec: "#121212",
      acc: "#F3F3F3",
      txt: "#000000",
      ltxt: "#4b4949",
      wtxt: "#ffffff",
    },
    "Modern Dark": {
      pri: "#121212",
      sec: "#292929",
      acc: "#3A3A3A",
      txt: "#FFFFFF",
      ltxt: "#A8A8A8",
      wtxt: "#ffffff",
    },
    "Milt Blue": {
      pri: "#ffffff",
      sec: "#03113a",
      acc: "#f0fcff",
      txt: "#040849",
      ltxt: "#4b4949",
      wtxt: "#ffffff",
    },
    "Soft Breeze": {
      pri: "#F8FAFC",
      sec: "#002c47",
      acc: "#A2D2FF",
      txt: "#374151",
      ltxt: "#64748B",
      wtxt: "#FFFFFF",
    },
  };
  
  export const allCssColors = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "grey",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
  ];
  
  
  
  export const variationSuggestions = [
    {
      name: 'Color',
      options: [
        "aliceblue", "antiquewhite", "aqua", "aquamarine", "azure", "beige", "bisque", "black", 
        "blanchedalmond", "blue", "blueviolet", "brown", "burlywood", "cadetblue", "chartreuse", 
        "chocolate", "coral", "cornflowerblue", "cornsilk", "crimson", "cyan", "darkblue", "darkcyan", 
        "darkgoldenrod", "darkgray", "darkgreen", "darkgrey", "darkkhaki", "darkmagenta", "darkolivegreen", 
        "darkorange", "darkorchid", "darkred", "darksalmon", "darkseagreen", "darkslateblue", 
        "darkslategray", "darkslategrey", "darkturquoise", "darkviolet", "deeppink", "deepskyblue", 
        "dimgray", "dimgrey", "dodgerblue", "firebrick", "floralwhite", "forestgreen", "fuchsia", 
        "gainsboro", "ghostwhite", "gold", "goldenrod", "gray", "green", "greenyellow", "grey", 
        "honeydew", "hotpink", "indianred", "indigo", "ivory", "khaki", "lavender", "lavenderblush", 
        "lawngreen", "lemonchiffon", "lightblue", "lightcoral", "lightcyan", "lightgoldenrodyellow", 
        "lightgray", "lightgreen", "lightgrey", "lightpink", "lightsalmon", "lightseagreen", 
        "lightskyblue", "lightslategray", "lightslategrey", "lightsteelblue", "lightyellow", 
        "lime", "limegreen", "linen", "magenta", "maroon", "mediumaquamarine", "mediumblue", 
        "mediumorchid", "mediumpurple", "mediumseagreen", "mediumslateblue", "mediumspringgreen", 
        "mediumturquoise", "mediumvioletred", "midnightblue", "mintcream", "mistyrose", "moccasin", 
        "navajowhite", "navy", "oldlace", "olive", "olivedrab", "orange", "orangered", "orchid", 
        "palegoldenrod", "palegreen", "paleturquoise", "palevioletred", "papayawhip", "peachpuff", 
        "peru", "pink", "plum", "powderblue", "purple", "rebeccapurple", "red", "rosybrown", 
        "royalblue", "saddlebrown", "salmon", "sandybrown", "seagreen", "seashell", "sienna", "silver", 
        "skyblue", "slateblue", "slategray", "slategrey", "snow", "springgreen", "steelblue", "tan", 
        "teal", "thistle", "tomato", "turquoise", "violet", "wheat", "white", "whitesmoke", "yellow", 
        "yellowgreen"
      ],
    },
    {
      name: 'Size',
      options: ['XS', 'S', 'M', 'L', 'XL'],
    },
    {
      name: 'Material',
      options: [
        "Cotton", "Polyester", "Wool", "Silk", "Leather", "Linen", "Denim", "Fleece", "Rayon", 
        "Nylon", "Spandex", "Velvet", "Cashmere", "Bamboo", "Faux Fur", "Taffeta", "Satin", "Chiffon"
      ],
    },
    {
      name: 'Pattern',
      options: [
        "Solid", "Striped", "Checked", "Plaid", "Polka Dot", "Floral", "Paisley", "Animal Print", 
        "Camouflage", "Geometric", "Houndstooth", "Abstract", "Tie-Dye", "Leopard Print", "Chevron"
      ],
    },
    {
      name: 'Gender',
      options: [
        "Men", "Women", "Unisex", "Boys", "Girls", "Kids", "Teens"
      ],
    },
    {
      name: 'Brand',
      options: [
        "Nike", "Adidas", "Puma", "Under Armour", "Reebok", "Converse", "New Balance", "Vans", 
        "Jordan", "Asics", "Skechers", "Fila", "Tommy Hilfiger", "Calvin Klein", "Levi's", 
        "Wrangler", "H&M", "Zara", "Uniqlo", "Gucci", "Prada"
      ],
    },
    {
      name: 'Fit',
      options: [
        "Slim Fit", "Regular Fit", "Loose Fit", "Athletic Fit", "Relaxed Fit", "Tight Fit", "Boxy Fit", 
        "Crop Fit", "Oversized Fit", "Standard Fit"
      ],
    },
    {
      name: 'Occasion',
      options: [
        "Casual", "Formal", "Party", "Work", "Wedding", "Evening", "Vacation", "Sports", "Outdoor", 
        "Business", "Cocktail", "Bridal", "Festive", "Holiday"
      ],
    },
    {
      name: 'Season',
      options: [
        "Spring", "Summer", "Autumn", "Winter", "Year-round"
      ],
    },
    {
      name: 'Style',
      options: [
        "Bohemian", "Casual", "Streetwear", "Athleisure", "Chic", "Elegant", "Vintage", "Preppy", 
        "Minimalist", "Edgy", "Classic", "Trendy", "Sporty", "Urban", "Modern"
      ],
    },
  ];
  